name: Python unit tests  # This is the name of the GitHub Actions workflow
 
# This section specifies the events that will trigger the workflow
on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - '**'  # Triggers on pull requests to any branch
 
# This section defines the job that will be executed as part of the workflow
jobs:
  build:
    # This specifies the runner (virtual machine) on which the job will be executed
    runs-on: ubuntu-latest
 
    # This section defines the steps that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3 # Updated to v3 for compatibility with Node.js 16 and 20
    - name: Set up Python # Sets up the Python environment
      uses: actions/setup-python@v4 # Updated to v4 for compatibility with Node.js 16 and 20
      with:
        python-version: '3.12' # Specifies the Python version to use
 
    # This step installs the required dependencies for the project
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
 
    # This step runs the tests for the Python application
    - name: Run tests
      run: |
        python -m unittest discover -s tests